title: <p align="right"> Akash Mishra </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mishra-akash-0103/">LinkedIn</a> |
  <a href="https://github.com/akash-mishra01/">GitHub</a>
  </p>
  <p align='right'>
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Worked with Kyndryl in AI-Ops team.
  Working as Python/shell/Database developer in BFS domain for 11 years.
  <br>
  </p>



theme: jekyll-theme-minimal
